# Exploring factors associated with the popularity of the game

### A potential client is considering releasing the game within the scope of the following genres: *city builder, survival horror, rts, colony sim, tower defense*. We will be using the current data from Steam to analyse factors associated with the success of the games, in particular the time of the release and the pricing

> Data was sourced from Kaggle https://www.kaggle.com/datasets/fronkongames/steam-games-dataset on 12.07.2026, so will be reflective of all the releases and available data prior to this date

In [1]:
# Firstly, we will need to import all the required libraries to proceed with the data analysis
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

# Setting the option to see all the columns in the preview to ensure all information is captured
pd.set_option('display.max_columns', None)

In [2]:
# We will now read in the file
try:
    games_data = pd.read_csv("games.csv")
except FileNotFoundError:
    print("\n!ERROR!" \
    "\nThe file you're trying to load is not found. Make sure to check the spelling and " \
    "punctuation and try again")
    raise SystemExit("Stop right there! Please see the error message above!")

In [3]:
# Proceeding to previewing the data to estimate what can be deleted
games_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,Full audio languages,Reviews,Header image,Website,Support url,Support email,Windows,Mac,Linux,Metacritic score,Metacritic url,User score,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com,True,False,False,0,NaN,0,252,3,NaN,0,231,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net,True,True,False,0,NaN,0,21,3,NaN,0,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],['Korean'],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,yujingamesc@gmail.com,True,False,False,0,NaN,0,0,0,NaN,19,0,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],['English'],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [4]:
# Checking that the last column consists of only NaN
games_data["Movies"].isna().all()

np.True_

### From the preview we can clearly see the initial issue with the data, as the two columns merged into one (DiscountDCL count) causing a shift of the data. The dataframe also did not read the AppID correctly, leading to a skeweness of the dataframe by one column to the left causing the 'Movies' column to be completely NaN. We will need to address this before proceeding with the further analysis

In [5]:
# We will need to get the names of the columns to confirm this hypothesis and proceed with the 
# data transformation
cols = games_data.columns.tolist()
print(cols)

['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DiscountDLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

In [6]:
# Proceeding with the fixing and separating the columns to reflect the data correctly
fixed = []
for col in cols:
    if col == 'DiscountDLC count':
        fixed += ['Discount', 'DLC count']
    else:
        fixed.append(col)

games_data = pd.read_csv('games.csv', header=0, names=fixed)
print(games_data.columns.to_list())

['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'Discount', 'DLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

In [7]:
# Checking that the fix worked and the data is now presented correctly
games_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,Supported languages,Full audio languages,Reviews,Header image,Website,Support url,Support email,Windows,Mac,Linux,Metacritic score,Metacritic url,User score,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com,True,False,False,0,NaN,0,252,3,NaN,0,231,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net,True,True,False,0,NaN,0,21,3,NaN,0,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],['Korean'],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,yujingamesc@gmail.com,True,False,False,0,NaN,0,0,0,NaN,19,0,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],['English'],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

Now that we've got all the columns aligned with the correct representative information we will proceed with further evaluating the data and ensuring the data is being shown correctly

In [8]:
games_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125855 non-null  int64
 1   Name                        125854 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  str
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  int64
 6   Price                       125855 non-null  float64
 7   Discount                    125855 non-null  int64
 8   DLC count                   125855 non-null  int64
 9   About the game              117393 non-null  str
 10  Supported languages         125855 non-null  str
 11  Full audio languages        125855 non-null  str
 12  Reviews                     12181 non-null   str
 13  Header image                125774 non-null  str
 14  Website                     50520 non-null   str
 15  Support url                 55295 non-null   str
 16  Support email               103225 non-null  str
 17  Windows                     125855 non-null  bool
 18  Mac                         125855 non-null  bool
 19  Linux                       125855 non-null  bool
 20  Metacritic score            125855 non-null  int64
 21  Metacritic url              4258 non-null    str
 22  User score                  125855 non-null  int64
 23  Positive                    125855 non-null  int64
 24  Negative                    125855 non-null  int64
 25  Score rank                  40 non-null      float64
 26  Achievements                125855 non-null  int64
 27  Recommendations             125855 non-null  int64
 28  Notes                       23310 non-null   str
 29  Average playtime forever    125855 non-null  int64
 30  Average playtime two weeks  125855 non-null  int64
 31  Median playtime forever     125855 non-null  int64
 32  Median playtime two weeks   125855 non-null  int64
 33  Developers                  117406 non-null  str
 34  Publishers                  116933 non-null  str
 35  Categories                  116889 non-null  str
 36  Genres                      117432 non-null  str
 37  Tags                        83353 non-null   str
 38  Screenshots                 119828 non-null  str
 39  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 403.9 MB

We can see now the full information and the data types of the correct columns. We will now identify and proceed with dropping the columns that will not contribute to our data analysis. These columns are:
- AppID (no relevance)
- About the game (no relevance)
- Header image (no relevance)
- Website (no relevance)
- Support url (no relevance)
- Support email (no relevance)
- Metacritic url (no relevance)
- Score rank (not enough sufficient data to deal with missing values)
- Average playtime two weeks (want the all time data only)
- Median playtime two weeks (want the all time data only)
- Developers (no relevance)
- Publishers (no relevance)
- Tags (no relevance)
- Screenshots (no relevance)
- Movies (no relevance)
- Notes (no relevance)

In [9]:
# Dropping the columns
games_data_reduced = games_data.drop(columns=['AppID', 'About the game', 'Header image', 'Website', 
                                              'Support url', 'Support email', 'Metacritic url', 'Score rank',
                                              'Average playtime two weeks', 'Median playtime two weeks',
                                              'Developers', 'Publishers', 'Tags', 'Screenshots', 'Movies', 'Notes'])
games_data_reduced.head()

,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,Supported languages,Full audio languages,Reviews,Windows,Mac,Linux,Metacritic score,User score,Positive,Negative,Achievements,Recommendations,Average playtime forever,Median playtime forever,Categories,Genres
0,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,[],[],NaN,True,False,False,0,0,0,0,0,0,0,0,NaN,NaN
1,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,['English'],[],NaN,True,False,False,0,0,252,3,0,231,8,8,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure
2,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"['English', 'French', 'German', 'Russian']",[],NaN,True,True,False,0,0,21,3,0,0,0,0,"Single-player,Family Sharing",Casual
3,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,['Korean'],['Korean'],NaN,True,False,False,0,0,0,0,19,0,0,0,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation"
4,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,['English'],['English'],NaN,True,False,False,0,0,0,0,0,0,0,0,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access"

# Missing Values and Data quality inspection

Now that we have reduced the dataframe only to the relevant columns we can move onto dealing with the missing values in the columns

In [10]:
games_data_reduced.info()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Name                      125854 non-null  str
 1   Release date              125855 non-null  str
 2   Estimated owners          125855 non-null  str
 3   Peak CCU                  125855 non-null  int64
 4   Required age              125855 non-null  int64
 5   Price                     125855 non-null  float64
 6   Discount                  125855 non-null  int64
 7   DLC count                 125855 non-null  int64
 8   Supported languages       125855 non-null  str
 9   Full audio languages      125855 non-null  str
 10  Reviews                   12181 non-null   str
 11  Windows                   125855 non-null  bool
 12  Mac                       125855 non-null  bool
 13  Linux                     125855 non-null  bool
 14  Metacritic score          125855 non-null  int64
 15  User score                125855 non-null  int64
 16  Positive                  125855 non-null  int64
 17  Negative                  125855 non-null  int64
 18  Achievements              125855 non-null  int64
 19  Recommendations           125855 non-null  int64
 20  Average playtime forever  125855 non-null  int64
 21  Median playtime forever   125855 non-null  int64
 22  Categories                116889 non-null  str
 23  Genres                    117432 non-null  str
dtypes: bool(3), float64(1), int64(12), str(8)
memory usage: 51.1 MB

From the cell above we can see that the columns 'Reviews', 'Categories' and 'Genres' are the ones with the majority of the missing values. There is one row with the missing 'Name'. We will proceed to exploring the quality of the existing data in these columns to come to a decision regarding how to handle the missing data.

In [12]:
print(f"The unique values for Reviews is: \n{games_data_reduced['Reviews'].unique()}")

The unique values for Reviews is:
<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nan,
 '“And this is the very reason why I believe Fantasy General 2: Invasion has not only tremendous staying power, but the potential of a fulfilling future.” 9 – Turn Based Lovers “Graphically, I found the game beautiful, the music even great (the main track has been remastered from the original). The dialogue text and story depth is completely sufficient for me. Even though the balance of the game is not perfect and the level of difficulty is so high that it just cannot be done without reloading and optimizing, I still recommend any lover of turn-based games to buy it. Otherwise, you'll miss one of the most challenging and gripping genre representatives of the year!” 9.0 – Gamersglobal “Like its predecessor, Fantasy General 2 captivates from the first mission and even improves a lot of things from the original: The moral system is more transparent, the missions with their very different goals and many side locations are much more dynamic. I am moved to try everything to prevent my heroes and experienced units from perishingr. Again and again I am faced with risky decisions: Should I follow the fleeing enemy with my decimated troops? Or rather rest at the risk that the refugees will reform themselves? This is how to make a worthy, contemporary successor to a decades-old classic!” 86 – Gamestar',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '“Accolade did a great job with the conversion of the two styles. It has opened up a whole new field which I'm sure others will attempt to mimic. Steady balance of in car and on foot gameplay with explosive graphics. If you're an action fan, your money has probably grown dusty, it's time to brush it off.” 90 – Gaming Entertainment Monthly “Overall, I find the game quite enjoyable. While I believe it would have profited from things like bodywork damage and better strafing, it’s perfectly playable nonetheless, and is definitely worth checking out.” 88 – Game Over Online',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '“The gameplay is tight, the music and visuals are both fresh and nostalgic, and the roguelike tower aspect and difficulty will have you coming back for “just one more run” until you ascend to the top.” 90/100 – Nintendo World Report “[Roguelite] Genre fans will certainly enjoy the challenge, while newcomers will get plenty of enjoyment from the turn-based action as they master tile movement and placement.” 80/100 – The Xbox Hub “If Into The Breach was your cup of tea and you’re looking for something with that kind of flavor, Evertried is here to take you to new heights.” 70/100 – Hey Poor Player',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '“Bad North strips away just the right amount of complexity and headache that real-time strategy games tend to have, resulting in a core experience that is challenging, rewarding, and very replayable.” 4/5 – StrategyGamer “Do not be fooled by the cute sound effects or adorable sprites: Bad North is not a lovely new friend. It's here to steal your time, beat you up and possibly burn your house down.” 78/100 – PCGamer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '“Shrimply the best” 10/10 – Some weirdo on steam',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             '“Epic Arena is one of my favorite games this year. Addictive gameplay, an inspired visual design and a ridiculously fair freemium mechanic will keep me coming back for more.” 9/10 – Arcade Sushi “Epic Arena delivers an experience that abides by the age-old design philosophy of “easy to learn and hard to master,” all while being free-to-play.” 4/5 – 148 Apps “Consider Epic Arena an excellent blend between casual and high-pressure, fast-paced, strategic play. It offers something for most player types and it is doing so in a well-packaged manner, with an attention to detail in both gameplay and user experience.” 8.4/10 –',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '“Bright, bold, and loud is the Metronomicon, and though it has a namesake broiled in evil, the game is pure, unfiltered goodness.” 90 – Gaming Trend “this is one killer soundtrack” 9/10 – TechRaptor “The Metronomicon offers fun characters, a solid and wacky story line, strategic elements and some really great tunes” 85/100 – COGConnected',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '“...from the mysterious beginnings all the way to the jaw-dropping finale, this is a tale which delivers on its promise and then some.” 100 – Xbox Hub “It was just so good I didn’t want it to end.” 90 – BonusStage “Evan's Remains is one of my favorite games of 2020” GameSpot',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '“The most ambitious in the modern trilogy” 9/10 – IGN “A must-play” 4.5/5 – Hardcore Gamer “One of Lara Croft’s best modern adventures” 84/100 – PC Gamer',
 ...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '“Packed with intense, zombie-movie-style chases, along with a generous helping of absurdity” Bloody Disgusting “Give this a look as it’s one of the better runner games out there” Vulgar Knight “Full of charm, feels like a forgotten PS2 cult classic” deathtrips',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             '“The platforming is best-in-class, the characters and world left more of a mark than I expected, and Fabraz somehow managed to make going open-world seem both effortless and obvious.” 4.5/5 – TheGamer “Demon Tides exceeded almost all of my expectations for this 3D platformer. The mechanics are tight and sound, with a great level of customization to modify our moveset in unique ways that cater to how we want to play.” 90/100 – SteamDeckHQ “Demon Tides is a 3D platformer that'll be hard to top in 2026, with exquisite movement, tons of variety, and so many ways to kit out Beebz.” 90/100 – Loot Level Chill',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               '“So far, I’ve thoroughly enjoyed my time in Gloria Victis. (...) It’s a ridiculously fun time.”',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       '“Star Trek: Voyager - Across the Unknown lets dreams of Trekkies come true.” 75/100 – PC Games “This is perhaps the Star Trek game most faithful to its source material” 85/100 – Stevivor “In our review, we wished we would never arrive on Earth.” 80/100 – GameStar',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '“/” / – /',

It appears unclear on whether the reviews column is sourced as one review or combination of different reviews for the game, therefore due to the lack of this clarity it was decided to drop this column from the final analysis.

In [ ]:
games_data_reduced = games_data_reduced.drop(columns='Reviews')

In [19]:
games_data_reduced.head()

,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,Supported languages,Full audio languages,Windows,Mac,Linux,Metacritic score,User score,Positive,Negative,Achievements,Recommendations,Average playtime forever,Median playtime forever,Categories,Genres
0,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,[],[],True,False,False,0,0,0,0,0,0,0,0,NaN,NaN
1,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,['English'],[],True,False,False,0,0,252,3,0,231,8,8,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure
2,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"['English', 'French', 'German', 'Russian']",[],True,True,False,0,0,21,3,0,0,0,0,"Single-player,Family Sharing",Casual
3,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,['Korean'],['Korean'],True,False,False,0,0,0,0,19,0,0,0,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation"
4,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,['English'],['English'],True,False,False,0,0,0,0,0,0,0,0,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access"

> Plan to complete during the next session:
> 1. Finalise cleaning the data and reshape the dates into a correct format
> 2. Tokenise different genres and categories (needs further research on how to approach)
> 3. Proceed with multiple linear regression exploring the impact of different factors on the success of the game (measured by how many people own it & play it all time)

In [13]:
print(f"The unique values for Reviews is: \n{games_data_reduced['Categories'].unique()}")

The unique values for Reviews is:
<ArrowStringArray>
[                                                                                                                                                                                                                         nan,
                                                                                                                                                               'Single-player,Steam Trading Cards,Steam Cloud,Family Sharing',
                                                                                                                                                                                               'Single-player,Family Sharing',
                                                                                                                                                                            'Single-player,Steam Achievements,Family Sharing',
                                                                                                                                                                    'Single-player,VR Only,Steam Leaderboards,Family Sharing',
                                                                                                                                                            'Single-player,Tracked Controller Support,VR Only,Family Sharing',
                                                                                                                                                                    'Single-player,Steam Workshop,Steam Cloud,Family Sharing',
                                                                                                                                                                       'Single-player,Full controller support,Family Sharing',
                                                                                                                                                    'Single-player,Steam Achievements,Full controller support,Family Sharing',
                                                                                                                         'Single-player,Steam Achievements,Full controller support,Steam Cloud,Family Sharing,Steam Timeline',
 ...
                                                                                           'Single-player,Multi-player,PvP,LAN PvP,Co-op,LAN Co-op,VR Only,Adjustable Difficulty,Playable without Timed Input,Family Sharing',
                                                    'Single-player,Steam Achievements,Camera Comfort,Custom Volume Controls,Playable without Timed Input,Save Anytime,Stereo Sound,Surround Sound,Steam Cloud,Family Sharing',
                                                                                                       'Single-player,Steam Achievements,Adjustable Difficulty,Keyboard Only Option,Save Anytime,Stereo Sound,Family Sharing',
                                                                                               'Single-player,VR Supported,Custom Volume Controls,Mouse Only Option,Playable without Timed Input,Stereo Sound,Family Sharing',
                                                                                                                     'Single-player,Camera Comfort,Playable without Timed Input,Save Anytime,Subtitle Options,Family Sharing',
    'Single-player,Steam Achievements,Camera Comfort,Color Alternatives,Custom Volume Controls,Adjustable Difficulty,Keyboard Only Option,Playable without Timed Input,Partial Controller Support,Steam Cloud,Family Sharing',
 'Single-player,Steam Achievements,Custom Volume Controls,Adjustable Difficulty,Playable without Timed Input,Save Anytime,Stereo Sound,Subtitle Options,Surround Sound,Partial Controller Support,Steam Cloud,Family Sharing',
                                                                                                                                              'Single-player,Custom Volume Controls,Save Anytime,Stereo Sound,Surround Sound',
                                                                          'Single-player,Steam Achievements,Camera Comfort,Color Alternatives,Adjustable Difficulty,Playable without Timed Input,Stereo Sound,Family Sharing',
                                                                                               'Single-player,Full controller support,Playable without Timed Input,Stereo Sound,Steam Cloud,Remote Play on TV,Family Sharing']
Length: 14059, dtype: str

In [14]:
print(f"The unique values for Reviews is: \n{games_data_reduced['Genres'].unique()}")

The unique values for Reviews is:
<ArrowStringArray>
[                                                                                             nan,
                                                                                      'Adventure',
                                                                                         'Casual',
                                                                        'Casual,Indie,Simulation',
                                                                            'Action,Early Access',
                                                                               'Action,Adventure',
                                                                            'Simulation,Strategy',
                                                                                   'Action,Indie',
                                                                                   'Casual,Indie',
                                                                   'Action,Casual,Indie,Strategy',
 ...
                                                     'Action,Indie,RPG,Early Access,Free To Play',
                                                 'Casual,Free To Play,Audio Production,Utilities',
                                   'Action,Adventure,Massively Multiplayer,Strategy,Early Access',
                                                              'Action,Racing,Simulation,Strategy',
 'Casual,Indie,RPG,Simulation,Sports,Strategy,Animation & Modeling,Game Development,Early Access',
                                     'Casual,Massively Multiplayer,RPG,Free To Play,Early Access',
   'Free To Play,Animation & Modeling,Design & Illustration,Photo Editing,Utilities,Early Access',
                    'Simulation,Free To Play,Accounting,Education,Software Training,Early Access',
                                             'Casual,Sports,Strategy,Education,Software Training',
                                               'Action,Indie,Massively Multiplayer,Racing,Sports']
Length: 2923, dtype: str

In [17]:
games_data_reduced['Genres'].notna().value_counts()

Genres
True     117432
False      8423
Name: count, dtype: int64

In [11]:
'''for column in games_data.columns:
    print(f"Unique values for {column} are: ")
    print(games_data[column].unique())
    print("----------------------------------------------")'''

'for column in games_data.columns:\n    print(f"Unique values for {column} are: ")\n    print(games_data[column].unique())\n    print("----------------------------------------------")'